### ISSUE TITLE
Killing gopls makes vim hang

### ISSUE THREAD

**Issue by frioux** [govim/govim#1123]
### What version of Vim/Gvim are you using?

<details><summary>Vim/Gvim version</summary><br><pre>
$ vim --version
VIM - Vi IMproved 8.1 (2018 May 18, compiled Nov 08 2021 14:21:34)
Included patches: 1-2269
Modified by team+vim@tracker.debian.org
Compiled by team+vim@tracker.debian.org
Huge version with GTK3 GUI.  Features included (+) or not (-):
+acl               -farsi             -mouse_sysmouse    -tag_any_white
+arabic            +file_in_path      +mouse_urxvt       +tcl
+autocmd           +find_in_path      +mouse_xterm       +termguicolors
+autochdir         +float             +multi_byte        +terminal
-autoservername    +folding           +multi_lang        +terminfo
+balloon_eval      -footer            -mzscheme          +termresponse
+balloon_eval_term +fork()            +netbeans_intg     +textobjects
+browse            +gettext           +num64             +textprop
++builtin_terms    -hangul_input      +packages          +timers
+byte_offset       +iconv             +path_extra        +title
+channel           +insert_expand     +perl              +toolbar
+cindent           +job               +persistent_undo   +user_commands
+clientserver      +jumplist          +postscript        +vartabs
+clipboard         +keymap            +printer           +vertsplit
+cmdline_compl     +lambda            +profile           +virtualedit
+cmdline_hist      +langmap           -python            +visual
+cmdline_info      +libcall           +python3           +visualextra
+comments          +linebreak         +quickfix          +viminfo
+conceal           +lispindent        +reltime           +vreplace
+cryptv            +listcmds          +rightleft         +wildignore
+cscope            +localmap          -ruby              +wildmenu
+cursorbind        +lua               +scrollbind        +windows
+cursorshape       +menu              +signs             +writebackup
+dialog_con_gui    +mksession         +smartindent       +X11
+diff              +modify_fname      +sound             -xfontset
+digraphs          +mouse             +spell             +xim
+dnd               +mouseshape        +startuptime       +xpm
-ebcdic            +mouse_dec         +statusline        +xsmp_interact
+emacs_tags        +mouse_gpm         -sun_workshop      +xterm_clipboard
+eval              -mouse_jsbterm     +syntax            -xterm_save
+ex_extra          +mouse_netterm     +tag_binary        
+extra_search      +mouse_sgr         -tag_old_static    
   system vimrc file: "$VIM/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "$VIM/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/usr/share/vim"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -pthread -I/usr/include/gtk-3.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib/x86_64-linux-gnu/dbus-1.0/include -I/usr/include/gtk-3.0 -I/usr/include/gio-unix-2.0 -I/usr/include/cairo -I/usr/include/pango-1.0 -I/usr/include/fribidi -I/usr/include/harfbuzz -I/usr/include/atk-1.0 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/uuid -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/glib-2.0 -I/usr/lib/x86_64-linux-gnu/glib-2.0/include -Wdate-time  -g -O2 -fdebug-prefix-map=/build/vim-BPbmc6/vim-8.1.2269=. -fstack-protector-strong -Wformat -Werror=format-security -D_REENTRANT -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -Wl,-E  -Wl,-Bsymbolic-functions -Wl,-z,relro -Wl,-z,now -Wl,--as-needed -o vim   -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0 -lSM -lICE -lXpm -lXt -lX11 -lXdmcp -lSM -lICE  -lm -ltinfo -lnsl  -lselinux  -lcanberra -lacl -lattr -lgpm -ldl  -L/usr/lib -llua5.2 -Wl,-E  -fstack-protector-strong -L/usr/local/lib  -L/usr/lib/x86_64-linux-gnu/perl/5.30/CORE -lperl -ldl -lm -lpthread -lcrypt  -L/usr/lib/python3.8/config-3.8-x86_64-linux-gnu -lpython3.8 -lcrypt -lpthread -ldl -lutil -lm -lm -L/usr/lib/x86_64-linux-gnu -ltcl8.6 -ldl -lz -lpthread -lm     

</pre></details>

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.17 linux/amd64

</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/frew/.cache/go-build"
GOENV="/home/frew/.config/go/env"
GOEXE=""
GOEXPERIMENT=""
GOFLAGS="-mod=readonly"
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GOINSECURE=""
GOMODCACHE="/home/frew/go/pkg/mod"
GONOPROXY=""
GONOSUMDB=""
GOOS="linux"
GOPATH="/home/frew/go"
GOPRIVATE=""
GOPROXY="https://proxy.golang.org"
GOROOT="/home/frew/sdk/go1.17"
GOSUMDB="sum.golang.org"
GOTMPDIR=""
GOTOOLDIR="/home/frew/sdk/go1.17/pkg/tool/linux_amd64"
GOVCS=""
GOVERSION="go1.17"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/dev/null"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/run/shm/go-build4003348305=/tmp/go-build -gno-record-gcc-switches"

</pre></details>

### What version/commit of `govim` are you using?
d9edfeee5

### What is the output of `:messages` in Vim?
Messages maintainer: Bram Moolenaar <Bram@vim.org>

### Do the Vim channel, `govim` or `gopls` log files show anything interesting?

```
2021-11-23T16:59:49.598416_#1: gopls stderr: SIGQUIT: quit
2021-11-23T16:59:49.598469_#1: gopls stderr: PC=0x47efb9 m=0 sigcode=0
2021-11-23T16:59:49.598485_#1: gopls stderr: 
2021-11-23T16:59:49.598495_#1: gopls stderr: goroutine 58 [syscall, 3 minutes]:
2021-11-23T16:59:49.598506_#1: gopls stderr: syscall.Syscall(0x0, 0x0, 0xc0003ae000, 0x1000)
2021-11-23T16:59:49.598517_#1: gopls stderr:    /home/frew/sdk/go1.17/src/syscall/asm_linux_amd64.s:20 +0x5 fp=0xc0002a15a8 sp=0xc0002a15a0 pc=0x47efa5
2021-11-23T16:59:49.598529_#1: gopls stderr: syscall.read(0xc0000b8000, {0xc0003ae000, 0xc0002a1648, 0x0})
2021-11-23T16:59:49.598538_#1: gopls stderr:    /home/frew/sdk/go1.17/src/syscall/zsyscall_linux_amd64.go:687 +0x4d fp=0xc0002a1600 sp=0xc0002a15a8 pc=0x47c94d
2021-11-23T16:59:49.598548_#1: gopls stderr: syscall.Read(...)
2021-11-23T16:59:49.598559_#1: gopls stderr:    /home/frew/sdk/go1.17/src/syscall/syscall_unix.go:189
2021-11-23T16:59:49.598568_#1: gopls stderr: internal/poll.ignoringEINTRIO(...)
2021-11-23T16:59:49.598615_#1: gopls stderr:    /home/frew/sdk/go1.17/src/internal/poll/fd_unix.go:582
2021-11-23T16:59:49.598627_#1: gopls stderr: internal/poll.(*FD).Read(0xc0000b8000, {0xc0003ae000, 0x1000, 0x1000})
2021-11-23T16:59:49.598638_#1: gopls stderr:    /home/frew/sdk/go1.17/src/internal/poll/fd_unix.go:163 +0x285 fp=0xc0002a1680 sp=0xc0002a1600 pc=0x4a1465
2021-11-23T16:59:49.598650_#1: gopls stderr: os.(*File).read(...)
2021-11-23T16:59:49.598660_#1: gopls stderr:    /home/frew/sdk/go1.17/src/os/file_posix.go:32
...
```
in the gopls log.

### How did you install `govim`?

Pathogen

### What did you do?

Opened vim in my home directory and killed gopls with `killall -3 gopls`

### What did you expect to see?
Nothing, but vim continue to function

### What did you see instead?
Vim hangs and stops responding to any input.

**Comment by cespare** [comment]
Duplicate of #963.
