### ISSUE TITLE
GoToDef panics with "unexpected parse mode" in some cases

### ISSUE THREAD

**Issue by vrischmann** [govim/govim#763]
### What version of Vim/Gvim are you using?

<details><summary>Vim/Gvim version</summary><br><pre>
$ vim --version

VIM - Vi IMproved 8.2 (2019 Dec 12, compiled Jan 27 2020 00:00:00)
Included patches: 1-158
Modified by <bugzilla@redhat.com>
Compiled by <bugzilla@redhat.com>
Huge version with GTK3 GUI.  Features included (+) or not (-):
+acl               -farsi             -mouse_sysmouse    -tag_old_static
+arabic            +file_in_path      +mouse_urxvt       -tag_any_white
+autocmd           +find_in_path      +mouse_xterm       -tcl
+autochdir         +float             +multi_byte        +termguicolors
-autoservername    +folding           +multi_lang        +terminal
+balloon_eval      -footer            -mzscheme          +terminfo
+balloon_eval_term +fork()            +netbeans_intg     +termresponse
+browse            +gettext           +num64             +textobjects
++builtin_terms    -hangul_input      +packages          +textprop
+byte_offset       +iconv             +path_extra        +timers
+channel           +insert_expand     +perl/dyn          +title
+cindent           +job               +persistent_undo   +toolbar
+clientserver      +jumplist          +popupwin          +user_commands
+clipboard         +keymap            +postscript        +vartabs
+cmdline_compl     +lambda            +printer           +vertsplit
+cmdline_hist      +langmap           +profile           +virtualedit
+cmdline_info      +libcall           -python            +visual
+comments          +linebreak         +python3/dyn       +visualextra
+conceal           +lispindent        +quickfix          +viminfo
+cryptv            +listcmds          +reltime           +vreplace
+cscope            +localmap          +rightleft         +wildignore
+cursorbind        +lua/dyn           +ruby/dyn          +wildmenu
+cursorshape       +menu              +scrollbind        +windows
+dialog_con_gui    +mksession         +signs             +writebackup
+diff              +modify_fname      +smartindent       +X11
+digraphs          +mouse             -sound             -xfontset
+dnd               +mouseshape        +spell             +xim
-ebcdic            +mouse_dec         +startuptime       +xpm
+emacs_tags        +mouse_gpm         +statusline        +xsmp_interact
+eval              -mouse_jsbterm     -sun_workshop      +xterm_clipboard
+ex_extra          +mouse_netterm     +syntax            -xterm_save
+extra_search      +mouse_sgr         +tag_binary        
   system vimrc file: "/etc/vimrc"
     user vimrc file: "$HOME/.vimrc"
 2nd user vimrc file: "~/.vim/vimrc"
      user exrc file: "$HOME/.exrc"
  system gvimrc file: "/etc/gvimrc"
    user gvimrc file: "$HOME/.gvimrc"
2nd user gvimrc file: "~/.vim/gvimrc"
       defaults file: "$VIMRUNTIME/defaults.vim"
    system menu file: "$VIMRUNTIME/menu.vim"
  fall-back for $VIM: "/etc"
 f-b for $VIMRUNTIME: "/usr/share/vim/vim82"
Compilation: gcc -c -I. -Iproto -DHAVE_CONFIG_H -DFEAT_GUI_GTK  -I/usr/include/gtk-3.0 -I/usr/include/pango-1.0 -I/usr/include/glib-2.0 -I/usr/lib64/glib-2.0/include -I/usr/include/harfbuzz -I/usr/include/fribidi -I/usr/include/freetype2 -I/usr/include/libpng16 -I/usr/include/cairo -I/usr/include/pixman-1 -I/usr/include/gdk-pixbuf-2.0 -I/usr/include/libmount -I/usr/include/blkid -I/usr/include/gio-unix-2.0 -I/usr/include/libdrm -I/usr/include/atk-1.0 -I/usr/include/at-spi2-atk/2.0 -I/usr/include/at-spi-2.0 -I/usr/include/dbus-1.0 -I/usr/lib64/dbus-1.0/include -pthread    -O2 -g -pipe -Wall -Werror=format-security -Wp,-D_GLIBCXX_ASSERTIONS -fexceptions -fstack-protector-strong -grecord-gcc-switches -specs=/usr/lib/rpm/redhat/redhat-hardened-cc1 -specs=/usr/lib/rpm/redhat/redhat-annobin-cc1 -m64 -mtune=generic -fasynchronous-unwind-tables -fstack-clash-protection -fcf-protection -D_GNU_SOURCE -D_FILE_OFFSET_BITS=64 -U_FORTIFY_SOURCE -D_FORTIFY_SOURCE=1       
Linking: gcc   -L. -Wl,-z,relro  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -fstack-protector-strong -rdynamic -Wl,-export-dynamic -Wl,--enable-new-dtags -Wl,-z,relro -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld  -Wl,-z,relro  -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -lpython3.7m -lcrypt -lpthread -ldl  -lutil -lm  -L/usr/local/lib -Wl,--as-needed -o vim   -lgtk-3 -lgdk-3 -lpangocairo-1.0 -lpango-1.0 -lharfbuzz -latk-1.0 -lcairo-gobject -lcairo -lgdk_pixbuf-2.0 -lgio-2.0 -lgobject-2.0 -lglib-2.0  -lSM -lICE -lXpm -lXt -lX11 -lSM -lICE  -lm  -lselinux  -lncurses -lacl -lattr -lgpm -ldl   -Wl,--enable-new-dtags -Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -Wl,-z,relro -Wl,--as-needed -Wl,-z,now -specs=/usr/lib/rpm/redhat/redhat-hardened-ld -fstack-protector-strong -L/usr/local/lib  -L/usr/lib64/perl5/CORE -lperl -lpthread -lresolv -ldl -lm -lcrypt -lutil -lc        

</pre></details>

### What version of Go are you using (`go version`)?

<pre>
$ go version
go version go1.13.6 linux/amd64
</pre>

### What operating system and processor architecture are you using (`go env`)?

<details><summary><code>go env</code> Output</summary><br><pre>
$ go env
GO111MODULE=""
GOARCH="amd64"
GOBIN=""
GOCACHE="/home/vincent/.cache/go-build"
GOENV="/home/vincent/.config/go/env"
GOEXE=""
GOFLAGS=""
GOHOSTARCH="amd64"
GOHOSTOS="linux"
GONOPROXY="github.com/gocql/gocql,golang.org/x/net"
GONOSUMDB="github.com/gocql/gocql,golang.org/x/net"
GOOS="linux"
GOPATH="/home/vincent/dev/go"
GOPRIVATE="github.com/gocql/gocql,golang.org/x/net"
GOPROXY="direct"
GOROOT="/usr/lib/golang"
GOSUMDB="off"
GOTMPDIR=""
GOTOOLDIR="/usr/lib/golang/pkg/tool/linux_amd64"
GCCGO="gccgo"
AR="ar"
CC="gcc"
CXX="g++"
CGO_ENABLED="1"
GOMOD="/home/vincent/.vim/pack/plugins/opt/govim/go.mod"
CGO_CFLAGS="-g -O2"
CGO_CPPFLAGS=""
CGO_CXXFLAGS="-g -O2"
CGO_FFLAGS="-g -O2"
CGO_LDFLAGS="-g -O2"
PKG_CONFIG="pkg-config"
GOGCCFLAGS="-fPIC -m64 -pthread -fmessage-length=0 -fdebug-prefix-map=/tmp/go-build069019116=/tmp/go-build -gno-record-gcc-switches"
</pre></details>

### What version/commit of `govim` are you using?

b7d5290fc7ce81ab80b9485a0a72f1406172f1d9

### What is the output of `:messages` in Vim?

I'm unable to run it because after the failure I encounter vim is frozen.

### Do the Vim channel, `govim` or `gopls` log files show anything interesting?

```
2020-02-07T13:52:39.575065_#1: run: waiting to read a JSON message
2020-02-07T13:52:39.575280_#1: gopls server start =======================
2020-02-07T13:52:39.575280_#1: gopls.Definition() call; params:
2020-02-07T13:52:39.575280_#1: &protocol.DefinitionParams{
2020-02-07T13:52:39.575280_#1:     TextDocumentPositionParams: protocol.TextDocumentPositionParams{
2020-02-07T13:52:39.575280_#1:         TextDocument: protocol.TextDocumentIdentifier{URI:"file:///home/vincent/dev/go/pkg/mod/gitlab.foobar.com/gomodules/protoss@v1.2.8/stuff/otherstuff/otherstuff.pb.go"},
2020-02-07T13:52:39.575280_#1:         Position:     protocol.Position{Line:492, Character:26},
2020-02-07T13:52:39.575280_#1:     },
2020-02-07T13:52:39.575280_#1:     WorkDoneProgressParams: protocol.WorkDoneProgressParams{},
2020-02-07T13:52:39.575280_#1:     PartialResultParams:    protocol.PartialResultParams{},
2020-02-07T13:52:39.575280_#1: }
2020-02-07T13:52:39.575280_#1: gopls server end =======================
2020-02-07T13:52:39.575716_#1: gopls server start =======================
2020-02-07T13:52:39.575716_#1: gopls.Definition() return; err: method "textDocument/definition" did not reply; res:
2020-02-07T13:52:39.575716_#1: []protocol.Location(nil)
2020-02-07T13:52:39.575716_#1: gopls server end =======================
2020-02-07T13:52:39.575850_#1: got error whilst handling command:GOVIMGoToDef: failed to call gopls.Definition: method "textDocument/definition" did not reply
2020-02-07T13:52:39.575850_#1: params were: &protocol.DefinitionParams{
2020-02-07T13:52:39.575850_#1:     TextDocumentPositionParams: protocol.TextDocumentPositionParams{
2020-02-07T13:52:39.575850_#1:         TextDocument: protocol.TextDocumentIdentifier{URI:"file:///home/vincent/dev/go/pkg/mod/gitlab.foobar.com/gomodules/protoss@v1.2.8/stuff/otherstuff/otherstuff.pb.go"},
2020-02-07T13:52:39.575850_#1:         Position:     protocol.Position{Line:492, Character:26},
2020-02-07T13:52:39.575850_#1:     },
2020-02-07T13:52:39.575850_#1:     WorkDoneProgressParams: protocol.WorkDoneProgressParams{},
2020-02-07T13:52:39.575850_#1:     PartialResultParams:    protocol.PartialResultParams{},
2020-02-07T13:52:39.575850_#1: }
2020-02-07T13:52:39.575874_#1: vim start =======================
2020-02-07T13:52:39.575874_#1: sendJSONMsg: [91,["got error whilst handling command:GOVIMGoToDef: failed to call gopls.Definition: method \"textDocument/definition\" did not reply\nparams were: \u0026protocol.DefinitionParams{\n    TextDocumentPositionParams: protocol.TextDocumentPositionParams{\n        TextDocument: protocol.TextDocumentIdentifier{URI:\"file:///home/vincent/dev/go/pkg/mod/gitlab.foobar.com/gomodules/protoss@v1.2.8/stuff/otherstuff/otherstuff.pb.go\"},\n        Position:     protocol.Position{Line:492, Character:26},\n    },\n    WorkDoneProgressParams: protocol.WorkDoneProgressParams{},\n    PartialResultParams:    protocol.PartialResultParams{},\n}",""]]
2020-02-07T13:52:39.575874_#1: vim end =======================
2020-02-07T13:52:39.577962_#1: gopls stderr: panic: unexpected parse mode for gitlab.foobar.com/gomodules/protoss/stuff/otherstuff
2020-02-07T13:52:39.577977_#1: gopls stderr:
2020-02-07T13:52:39.577982_#1: gopls stderr: goroutine 12406 [running]:
2020-02-07T13:52:39.577988_#1: gopls stderr: golang.org/x/tools/internal/lsp/cache.expectMode(...)
2020-02-07T13:52:39.577992_#1: gopls stderr:    /home/vincent/dev/go/pkg/mod/golang.org/x/tools@v0.0.0-20200205190317-6e8b36d2c76b/internal/lsp/cache/snapshot.go:376
2020-02-07T13:52:39.577996_#1: gopls stderr: golang.org/x/tools/internal/lsp/cache.(*snapshot).shouldCheck(0xc001010240, 0xc0061963f8, 0x1, 0x1, 0xbcad80, 0x1, 0xd5e070, 0x8)
2020-02-07T13:52:39.578000_#1: gopls stderr:    /home/vincent/dev/go/pkg/mod/golang.org/x/tools@v0.0.0-20200205190317-6e8b36d2c76b/internal/lsp/cache/snapshot.go:204 +0x2d9
2020-02-07T13:52:39.578004_#1: gopls stderr: golang.org/x/tools/internal/lsp/cache.(*snapshot).packageHandles(0xc001010240, 0xe5ed60, 0xc0083e1140, 0xbc9600, 0xc007f8e6a0, 0xc0061963f8, 0x1, 0x1, 0x40db76, 0xc0083e1110, ...)
2020-02-07T13:52:39.578007_#1: gopls stderr:    /home/vincent/dev/go/pkg/mod/golang.org/x/tools@v0.0.0-20200205190317-6e8b36d2c76b/internal/lsp/cache/snapshot.go:133 +0x67
2020-02-07T13:52:39.578012_#1: gopls stderr: golang.org/x/tools/internal/lsp/cache.(*snapshot).PackageHandles(0xc001010240, 0xe5ed60, 0xc0083e1110, 0xe5cd20, 0xc00078b1c0, 0x6956dd, 0xc534c0, 0xc00b6d4c20, 0xc007ae78c0, 0xbf877545e24ee48a)
2020-02-07T13:52:39.578021_#1: gopls stderr:    /home/vincent/dev/go/pkg/mod/golang.org/x/tools@v0.0.0-20200205190317-6e8b36d2c76b/internal/lsp/cache/snapshot.go:85 +0x306
2020-02-07T13:52:39.578037_#1: gopls stderr: golang.org/x/tools/internal/lsp/source.getParsedFile(0xe5ed60, 0xc0083e1110, 0xe6eee0, 0xc001010240, 0xe5cd20, 0xc00078b1c0, 0xd5d098, 0xe5ed60, 0xc0083e1110, 0xc00b6d4c20, ...)
2020-02-07T13:52:39.578065_#1: gopls stderr:    /home/vincent/dev/go/pkg/mod/golang.org/x/tools@v0.0.0-20200205190317-6e8b36d2c76b/internal/lsp/source/util.go:71 +0x7d
2020-02-07T13:52:39.578069_#1: gopls stderr: golang.org/x/tools/internal/lsp/source.Identifier(0xe5ed60, 0xc0083e1110, 0xe6eee0, 0xc001010240, 0xe5cd20, 0xc00078b1c0, 0x407ec00000000000, 0x403a000000000000, 0x0, 0x0, ...)
2020-02-07T13:52:39.578075_#1: gopls stderr:    /home/vincent/dev/go/pkg/mod/golang.org/x/tools@v0.0.0-20200205190317-6e8b36d2c76b/internal/lsp/source/identifier.go:55 +0x133
2020-02-07T13:52:39.578094_#1: gopls stderr: golang.org/x/tools/internal/lsp.(*Server).definition(0xc0002d42a0, 0xe5ed60, 0xc008419950, 0xc00aa1e140, 0xc00aa1e140, 0x0, 0x0, 0x0, 0xc000696d10)
2020-02-07T13:52:39.578100_#1: gopls stderr:    /home/vincent/dev/go/pkg/mod/golang.org/x/tools@v0.0.0-20200205190317-6e8b36d2c76b/internal/lsp/definition.go:29 +0x1c6
2020-02-07T13:52:39.578123_#1: gopls stderr: golang.org/x/tools/internal/lsp.(*Server).Definition(0xc0002d42a0, 0xe5ed60, 0xc008419950, 0xc00aa1e140, 0xc00aa1e140, 0x0, 0x0, 0xc001c1e438, 0xc001c1e430)
2020-02-07T13:52:39.578130_#1: gopls stderr:    /home/vincent/dev/go/pkg/mod/golang.org/x/tools@v0.0.0-20200205190317-6e8b36d2c76b/internal/lsp/server_gen.go:32 +0x4d
2020-02-07T13:52:39.578171_#1: gopls stderr: golang.org/x/tools/internal/lsp/protocol.serverHandler.Deliver(0xe7cde0, 0xc0002d42a0, 0xe5ed60, 0xc008419950, 0xc00a9dfa40, 0xc008419900, 0xc00122b9f0)
2020-02-07T13:52:39.578180_#1: gopls stderr:    /home/vincent/dev/go/pkg/mod/golang.org/x/tools@v0.0.0-20200205190317-6e8b36d2c76b/internal/lsp/protocol/tsserver.go:389 +0x30b1
2020-02-07T13:52:39.578189_#1: gopls stderr: golang.org/x/tools/internal/jsonrpc2.(*Conn).Run.func1(0xc013b1b080, 0xc00a9dfa40, 0xc000294b40, 0xe5ed60, 0xc008419950, 0x0, 0x0, 0xc00ad6abd0)
2020-02-07T13:52:39.578197_#1: gopls stderr:    /home/vincent/dev/go/pkg/mod/golang.org/x/tools@v0.0.0-20200205190317-6e8b36d2c76b/internal/jsonrpc2/jsonrpc2.go:370 +0x170
2020-02-07T13:52:39.578201_#1: gopls stderr: created by golang.org/x/tools/internal/jsonrpc2.(*Conn).Run
2020-02-07T13:52:39.578212_#1: gopls stderr:    /home/vincent/dev/go/pkg/mod/golang.org/x/tools@v0.0.0-20200205190317-6e8b36d2c76b/internal/jsonrpc2/jsonrpc2.go:354 +0x877
```

### How did you install `govim`?

Vim 8 package

### What did you do?

In a file I call `:GOVIMGoToDef` on a type, which works fine. That type is a struct which is in a go module.
Then inside that struct I try to call `:GOVIMGoToDef` again on the type of a member field and that fails with the panic above.

After that the vim instance is unusable, I can't type anything and I need to kill vim.

I determined that the commit 897d5a4db22ce6931ebcd798cdf6be485825ed15 is responsible, by going back to faf4593ff2fda3536ffce9576f79e21799da0e89 it works fine.

### What did you expect to see?

I expect `:GOVIMGoToDef` to not cause a panic.

### What did you see instead?

`:GOVIMGoToDef` fails in some cases.

**Comment by leitzler** [comment]
Thanks for the report!

It looks like you ran into https://github.com/golang/go/issues/37045. It has been fixed, but we need to update tools version in `govim` to (at least) https://github.com/golang/tools/commit/7cfd24942e79e05685521b99b8f6c711489f9cb6.
